### ISSUE TITLE
Crashing When Modifying Configurations

### ISSUE THREAD

**Issue by vinceeleazar** [kyrptonaught/tooltipfix#1]
The game crashes when trying to access configs (any other mod) through Mod Menu with this mod installed. 
Here are the logs:
_Crash-report:_ https://paste.ee/p/ldasa
_Full-log:_ https://paste.ee/p/qoeSg

Hope this information will help you. Thanks for your time creating this wonderful mod!

**Comment by Mhowser** [comment]
I'm having the same problem https://pastebin.com/K0tfemzX

**Comment by kyrptonaught** [comment]
Thanks for the report, I'll take a look at this later today

**Comment by kyrptonaught** [comment]
1.0.1 should fix this

**Comment by vinceeleazar** [comment]
Thank you for the quick fix! Will close the issue.

**Comment by egeesin** [comment]
Somehow same error occurs when using Mod Menu with Turkish language. As soon as I hover on configure button, game crashes without showing the "Ayarla..."(Configure...) tooltip unless I disable ToolTipFix. Here's my console [output](https://hastebin.com/tuboliguma.yaml).

**Comment by kyrptonaught** [comment]
Does it crash on another language? Or just Turkish?

**Comment by egeesin** [comment]
I tried Polish too (which has one of the newest approved translations) but it showed the tooltip without a problem. I'm pretty sure that there's no syntax error in the tr_tr.json. Not my strongest guess but I have a suspicion that it may be something to do with the string length. I'll test different lengths and languages.

**Comment by kyrptonaught** [comment]
The error implies that it's due to an empty string, but there's a check above to prevent that from happening. Very odd

**Comment by egeesin** [comment]
Original string: "Configure..." (Total length is 12)
Polish string: "Skonfiguruj..." (Total length is 14)
Turkish string: "Ayarla..." (Total length is 9)
Chinese (Simplified) string: "配置…" (Total length is 3)
Italian string: "Configura" (Total length is 9)
Russian string: "Настроить..." (Total length is 12)
Brazillian Portuegese: "Configuração..." (Total length is 16)

Game crashed when language set to Turkish, Italian, Chinese (S) and
I think when tooltip length is above 12 the game doesn't crash.

Tried to add more dots to "Ayarla...". 
![Screen Shot 2020-11-15 at 2 54 52 PM](https://user-images.githubusercontent.com/8004972/99184250-878e8d00-2752-11eb-844e-d7a061a6ff38.png)
Didn't crash with 5 dots (with 12 total char)
Then tried with 12 dots and didn't crashed.
![Screen Shot 2020-11-15 at 3 02 15 PM](https://user-images.githubusercontent.com/8004972/99184402-8f9afc80-2753-11eb-89b2-a26f0c609895.png)
Also tried "————————————" (11x —) to prove tooltip width is irrelevant, then it crashed.

It should be the minimum string length and the position of the configure button. (very close to top-right edge.)

**Comment by kyrptonaught** [comment]
Ah can you update tooltipfix tp 1.0.2. I thought for sure I already fixed this, and just saw in your log that you're using an old version.
Thank you for the very in depth testing and investigation though!

**Comment by egeesin** [comment]
Ahh, my bad. Must have missed that one! I thought it was up to date, got worried there. There's no problem with 1.0.2 now, thanks!
