### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by xhendrikg** [kyrptonaught/tooltipfix#10]
![grafik](https://user-images.githubusercontent.com/69456711/126542047-563c045d-a5f5-4d0c-bc9f-6c099c69fd7d.png)
![grafik](https://user-images.githubusercontent.com/69456711/126542090-b2c4f240-0e47-48da-b5f8-5ae78f0cc54f.png)
![grafik](https://user-images.githubusercontent.com/69456711/126542136-ea6c2659-2ec8-4fd8-8760-614283aef6af.png)

**Comment by kyrptonaught** [comment]
You need to install the mod "fabric api". It's available on curseforge.
