### ISSUE TITLE
Compatibility: 1.0.3 breaks compatibility with Inspectio 

### ISSUE THREAD

**Issue by MeeniMc** [kyrptonaught/tooltipfix#12]
The latest 1.0.3 release breaks compatibility with mod Inspectio (1.1.0+1.17): some of the custom tooltips are not displayed (e.g., food items). 

Version 1.0.2 used to be compatible.

**Comment by kyrptonaught** [comment]
Can you link to the mod? I can't find it with a google search

**Comment by MeeniMc** [comment]
Sure thing, I got the name wrong actually https://modrinth.com/mod/inspecio

**Comment by kyrptonaught** [comment]
This was fixed in 1.0.4
