### ISSUE TITLE
Suggestion, Compatibility and Enhancement(?)

### ISSUE THREAD

**Issue by Laifsyn** [kyrptonaught/tooltipfix#15]
![image](https://user-images.githubusercontent.com/99366187/160039544-a15b5ffa-63d3-4e63-a515-3a07dd3da12d.png)
This is REI Tooltip
![image](https://user-images.githubusercontent.com/99366187/160039588-80ca8df0-6094-42b4-b8b8-c16ed6bf7b54.png)
This is tooltipfix(even though I have \n in CraftTweaker's script, it apparently doesn't reflect on Vanilla's tooltip. - Long Short, It's a long ass line without your mod)

```
var text1 = "Mix this in a big puddle with sand \nto produce Quartz Crystals" as string;
var text2 = "Press Shift for more info" as string;
<item:ae2:certus_quartz_dust>.
addShiftTooltip(((text1 + text2) as TextComponent).setStyle(Style.empty().withColor(c_cyan)),(text2 as TextComponent).setStyle(Style.empty().withColor(c_moreinfo)));

```
So, let it to be able to detect those \n linefeeds, and reflect them accordingly and probly even adjust the tooltip width with the  linefeed?

**Comment by kyrptonaught** [comment]
ToolTipFix 1.0.5(only for 1.19 at the moment) does have support for \n
