### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by Madis0** [kyrptonaught/tooltipfix#18]
You might want to publish to [Modrinth](https://modrinth.com) as well, as it is a growing mod platform.

**Comment by youmukonpaku1337** [comment]
yus pls do

**Comment by RaptaG** [comment]
I agree too!

**Comment by kyrptonaught** [comment]
I just uploaded them there now. I added 1.0.4 for 1.17 and 1.18. And 1.0.5 for 1.19.

Also tooltipfix basically being my most popular mod has received a grand total of 2 downloads on modrinth, compared to the 2.7million on curseforge :/

**Comment by Madis0** [comment]
Could you send the link? I was not able to find it from search...

**Comment by kyrptonaught** [comment]
Hm I think there is something wrong. I think someone who helped update the mod to 1.17 took ownership of the modrinth project. I'll try to contact them

**Comment by triphora** [comment]
Hey there, Modrinth admin here. The project has been a draft for ten months now, originally created by [jptrzy](https://modrinth.com/user/jptrzy). If you want me to transfer ownership to you, I can do so, just let me know.

**Comment by kyrptonaught** [comment]
Ah well that would explain the downloads haha. I wonder why they created it but did not publish it.

Transferring it would be great, thank you!

**Comment by triphora** [comment]
I somehow managed to mess it up and made you both co-owners. I've asked someone with DB access to make it so the other person is just a Member instead of an Owner :)
For it to be approved, you'll have to press the `Submit for review` button on [the project page](https://modrinth.com/mod/tooltipfix).

**Comment by kyrptonaught** [comment]
The mod is now processing. Thanks!

https://modrinth.com/mod/tooltipfix
