### ISSUE TITLE
It' s may not necessary to add the hyphen in Asian character.

### ISSUE THREAD

**Issue by HemyO** [kyrptonaught/tooltipfix#19]
In Chinese, Japanese, and Korean, it's unnecessary to add the hyphen "-" when breakline.
Is it possible to check by `Character.UnicodeBlock` or something else?

**Comment by kyrptonaught** [comment]
Can you see if this is fixed in 1.1.0?

**Comment by HemyO** [comment]
I'm sorry for feedbacking so late. It's fixed.
😊 Thank you!
