### ISSUE TITLE
Update Minecraft version tags for Modrinth and CurseForge

### ISSUE THREAD

**Issue by ghost** [kyrptonaught/tooltipfix#20]
Add the tag for Minecraft versions 1.19.1 and 1.19.2 on [Modrinth](https://modrinth.com/mod/tooltipfix/version/1.0.5-1.19) and [CurseForge](https://www.curseforge.com/minecraft/mc-mods/tooltipfix/files/3820437). The 1.0.5 mod version works perfectly fine in these Minecraft, as I tested.

**Comment by kyrptonaught** [comment]
Did these as well, thanks
