### ISSUE TITLE
Wrapping assumes mutable list

### ISSUE THREAD

**Issue by emilyploszaj** [kyrptonaught/tooltipfix#21]
Simple example in code [here](https://github.com/kyrptonaught/tooltipfix/blob/1.19/src/main/java/net/kyrptonaught/tooltipfix/Helper.java#L63), the list has elements removed, added, and replaced, which assumes the list supports mutable operations. This is true in vanilla contexts, but mods may render tooltips differently. I recently patched my mod to use mutable lists to combat this issue, I assume other mods may have to as well.

**Comment by kyrptonaught** [comment]
Ah this is a good point, I had overlooked the fact other mods may change this.

Looking into it
