### ISSUE TITLE
Can't start the game...

### ISSUE THREAD

**Issue by enzomtpYT** [kyrptonaught/tooltipfix#22]
Im sorry i know i don't give a lot of thing, but my game crashes when i start it ( no game windows appearing ), im using quilt on prism launcher, heavily modded, lot of the error lines are about ToolTipFix, that's why im coming here !

Here the [log file](https://mclo.gs/LJsE8QB). Hope you can help me !

Thank you in advance !
Your Cordialities
-enzomtp

**Comment by kyrptonaught** [comment]
Looks like you're running mc 1.19.3, I haven't had a chance to update the mod to the new version yet.

I'll have an update out shortly!

**Comment by enzomtpYT** [comment]
Oh ok thank you !

**Comment by kyrptonaught** [comment]
1.1.1-1.19.3 was released with 1.19.3 support
