### ISSUE TITLE
Empty lines are removed from tooltips

### ISSUE THREAD

**Issue by haykam821** [kyrptonaught/tooltipfix#26]
In item tooltips, lore lines with empty text are removed entirely. The following command gives the player an item that reproduces this issue:

```mcfunction
give @s minecraft:egg{display:{Lore:['{"text":"Line 1"}','{"text":""}','{"text":"Line 3"}']}}
```

Expected | Actual
--- | --
<img width="197" alt="Vanilla appearance of item tooltip" src="https://user-images.githubusercontent.com/24855774/215578270-cb91a9a0-bb96-4be4-a982-f64cc98e31bd.png"> | <img width="186" alt="Modded appearance of item tooltip" src="https://user-images.githubusercontent.com/24855774/215578464-4f0489d0-677c-4866-a64a-50ab1f277c56.png">

**Comment by kyrptonaught** [comment]
Egg
