### ISSUE TITLE
Minecraft is not responding [Multiconnect].

### ISSUE THREAD

**Issue by L0um15** [kyrptonaught/tooltipfix#3]
When Tooltip is being rendered as below:
Th-
-is
-a-
to-
-ol
-t-
-ip
it causes minecraft to not respond. Tooltip should be rendered on the left side of the mouse pointer, but it didn't.

**Comment by L0um15** [comment]
Ah, i forgot to mention that you can reproduce it by hovering on version button in direct connection screen with multiconnect

**Comment by kyrptonaught** [comment]
Are you using the latest release of tooltip fix? I'll investigate tomorrow

**Comment by L0um15** [comment]
I redownloaded whole game and now it works as it should.
