### ISSUE TITLE
Works with 1.20.6

### ISSUE THREAD

**Issue by MoriyaShiine** [kyrptonaught/tooltipfix#34]
I have tested the mod in a 1.20.6 instance and it works fine (no crashes, tooltip wraps as expected). Given 1.20.6 had a single change, it also must work with 1.20.5. I would appreciate if you updated the compatible versions on the Modrinth and Curseforge sites!

**Comment by LordEnder-Kitty** [comment]
Also appears to be working fine on 1.21.
