### ISSUE TITLE
It doesn't work (1.17)

### ISSUE THREAD

**Issue by EndlessLegends** [kyrptonaught/tooltipfix#8]
Expected behavior :
<img src="https://i.imgur.com/VOttReM.png" width="660" height="360">

Actual behavior :
<img src="https://i.imgur.com/fGgsjmM.png" width="660" height="360">

mod list :
<img src="https://i.imgur.com/2QMmLug.png" width="660" height="360">

`Is there any other way to activate it? Or is there something I misunderstood? I want to know how to use it. thank you.`

**Comment by kyrptonaught** [comment]
It would appear that it's not activating at all, must've messed something up on the 1.17 port. I'll investigate

**Comment by kyrptonaught** [comment]
This was fixed in 1.0.3, my apologies.
